---

- hosts: all
  connection: local
  tasks:

    - name: Create BD 
      aci_bd: 
        bd: '{{ bd_name }}'
        vrf: '{{ vrf_name }}'
        tenant: '{{ tenant_name }}'
        host: '{{ inventory_hostname }}'
        username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
        password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
        validate_certs: no
    - name: Create a subnet
      aci_bd_subnet:
        tenant: '{{ tenant_name }}'
        bd: '{{ bd_name }}'
        gateway: '{{ gateway }}'
        mask: '{{ mask }}'
        host: '{{ inventory_hostname }}'
        username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
        password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
        validate_certs: no

