---

- hosts: all
  connection: local
  tasks:

    # PREP
    - name: Show the content of the SSH Passphrase from AWX
      debug:
        msg: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
    - name: ensure tenant exists
      aci_tenant: 
        name: 'TenantTower'
        descr: 'tenant by Ansible'
        host: '{{ inventory_hostname }}'
        username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
        password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
        validate_certs: no

