---

- hosts: all
  connection: local
  tasks:

    - name: Create EPG
      aci_epg: 
        epg: '{{ epg_name }}'
        tenant: '{{ tenant_name }}'
        bd: '{{ bd_name }}'
        host: '{{ inventory_hostname }}'
        username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
        password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
        validate_certs: no

