---

- hosts: all
  connection: local
  tasks:

    - name: Create App
      aci_ap: 
        tenant: '{{ tenant_name }}'
        ap: '{{ app_name }}'
        host: '{{ inventory_hostname }}'
        username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
        password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
        validate_certs: no

